// TODO: Maybe just use AppConfig as needed and not even load it},

AppConfig = AppConfig || {};

AppConfig.prism_languages = [
    {'label': 'Markup', 'value': 'html'},
    {'label': 'CSS', 'value': 'css'},
    {'label': 'C-like', 'value': 'clike'},
    {'label': 'JavaScript', 'value': 'javascript'},
    {'label': 'ABAP', 'value': 'abap'},
    {'label': 'ActionScript', 'value': 'actionscript'},
    {'label': 'Ada', 'value': 'ada'},
    {'label': 'Apache Configuration', 'value': 'apacheconf'},
    {'label': 'APL', 'value': 'apl'},
    {'label': 'AppleScript', 'value': 'applescript'},
    {'label': 'AsciiDoc', 'value': 'asciidoc'},
    {'label': 'ASP.NET (C#)', 'value': 'aspnet'},
    {'label': 'AutoIt', 'value': 'autoit'},
    {'label': 'AutoHotkey', 'value': 'autohotkey'},
    {'label': 'Bash', 'value': 'bash'},
    {'label': 'BASIC', 'value': 'basic'},
    {'label': 'Batch', 'value': 'batch'},
    {'label': 'Bison', 'value': 'bison'},
    {'label': 'Brainfuck', 'value': 'brainfuck'},
    {'label': 'Bro', 'value': 'bro'},
    {'label': 'C', 'value': 'c'},
    {'label': 'C#', 'value': 'csharp'},
    {'label': 'C++', 'value': 'cpp'},
    {'label': 'CoffeeScript', 'value': 'coffeescript'},
    {'label': 'Crystal', 'value': 'crystal'},
    {'label': 'CSS Extras', 'value': 'css-extras'},
    {'label': 'D', 'value': 'd'},
    {'label': 'Dart', 'value': 'dart'},
    {'label': 'Diff', 'value': 'diff'},
    {'label': 'Docker', 'value': 'docker'},
    {'label': 'Eiffel', 'value': 'eiffel'},
    {'label': 'Elixir', 'value': 'elixir'},
    {'label': 'Erlang', 'value': 'erlang'},
    {'label': 'F#', 'value': 'fsharp'},
    {'label': 'Fortran', 'value': 'fortran'},
    {'label': 'Gherkin', 'value': 'gherkin'},
    {'label': 'Git', 'value': 'git'},
    {'label': 'GLSL', 'value': 'glsl'},
    {'label': 'Go', 'value': 'go'},
    {'label': 'GraphQL', 'value': 'graphql'},
    {'label': 'Groovy', 'value': 'groovy'},
    {'label': 'Haml', 'value': 'haml'},
    {'label': 'Handlebars', 'value': 'handlebars'},
    {'label': 'Haskell', 'value': 'haskell'},
    {'label': 'Haxe', 'value': 'haxe'},
    {'label': 'HTTP', 'value': 'http'},
    {'label': 'Icon', 'value': 'icon'},
    {'label': 'Inform 7', 'value': 'inform7'},
    {'label': 'Ini', 'value': 'ini'},
    {'label': 'J', 'value': 'j'},
    {'label': 'Jade', 'value': 'jade'},
    {'label': 'Java', 'value': 'java'},
    {'label': 'JSON', 'value': 'json'},
    {'label': 'Julia', 'value': 'julia'},
    {'label': 'Keyman', 'value': 'keyman'},
    {'label': 'Kotlin', 'value': 'kotlin'},
    {'label': 'LaTeX', 'value': 'latex'},
    {'label': 'Less', 'value': 'less'},
    {'label': 'LiveScript', 'value': 'livescript'},
    {'label': 'LOLCODE', 'value': 'lolcode'},
    {'label': 'Lua', 'value': 'lua'},
    {'label': 'Makefile', 'value': 'makefile'},
    {'label': 'Markdown', 'value': 'markdown'},
    {'label': 'MATLAB', 'value': 'matlab'},
    {'label': 'MEL', 'value': 'mel'},
    {'label': 'Mizar', 'value': 'mizar'},
    {'label': 'Monkey', 'value': 'monkey'},
    {'label': 'NASM', 'value': 'nasm'},
    {'label': 'nginx', 'value': 'nginx'},
    {'label': 'Nim', 'value': 'nim'},
    {'label': 'Nix', 'value': 'nix'},
    {'label': 'NSIS', 'value': 'nsis'},
    {'label': 'Objective-C', 'value': 'objectivec'},
    {'label': 'OCaml', 'value': 'ocaml'},
    {'label': 'Oz', 'value': 'oz'},
    {'label': 'PARI/GP', 'value': 'parigp'},
    {'label': 'Parser', 'value': 'parser'},
    {'label': 'Pascal', 'value': 'pascal'},
    {'label': 'Perl', 'value': 'perl'},
    {'label': 'PHP', 'value': 'php'},
    {'label': 'PHP Extras', 'value': 'php-extras'},
    {'label': 'PowerShell', 'value': 'powershell'},
    {'label': 'Processing', 'value': 'processing'},
    {'label': 'Prolog', 'value': 'prolog'},
    {'label': '.properties', 'value': 'properties'},
    {'label': 'Protocol Buffers', 'value': 'protobuf'},
    {'label': 'Puppet', 'value': 'puppet'},
    {'label': 'Pure', 'value': 'pure'},
    {'label': 'Python', 'value': 'python'},
    {'label': 'Q', 'value': 'q'},
    {'label': 'Qore', 'value': 'qore'},
    {'label': 'R', 'value': 'r'},
    {'label': 'React JSX', 'value': 'jsx'},
    {'label': 'reST (reStructuredText)', 'value': 'rest'},
    {'label': 'Rip', 'value': 'rip'},
    {'label': 'Roboconf', 'value': 'roboconf'},
    {'label': 'Ruby', 'value': 'ruby'},
    {'label': 'Rust', 'value': 'rust'},
    {'label': 'SAS', 'value': 'sas'},
    {'label': 'Sass (Sass)', 'value': 'sass'},
    {'label': 'Sass (Scss)', 'value': 'scss'},
    {'label': 'Scala', 'value': 'scala'},
    {'label': 'Scheme', 'value': 'scheme'},
    {'label': 'Smalltalk', 'value': 'smalltalk'},
    {'label': 'Smarty', 'value': 'smarty'},
    {'label': 'SQL', 'value': 'sql'},
    {'label': 'Stylus', 'value': 'stylus'},
    {'label': 'Swift', 'value': 'swift'},
    {'label': 'Tcl', 'value': 'tcl'},
    {'label': 'Textile', 'value': 'textile'},
    {'label': 'Twig', 'value': 'twig'},
    {'label': 'TypeScript', 'value': 'typescript'},
    {'label': 'Verilog', 'value': 'verilog'},
    {'label': 'VHDL', 'value': 'vhdl'},
    {'label': 'vim', 'value': 'vim'},
    {'label': 'Wiki markup', 'value': 'wiki'},
    {'label': 'Xojo (REALbasic)', 'value': 'xojo'},
    {'label': 'YAML', 'value': 'yaml'}
]

export default AppConfig
