// TODO: Maybe just use AppConfig as needed and not even load it},

AppConfig = AppConfig || {};

AppConfig.ace_editor_modes = [
    {'label': 'ABAP', 'value': 'ABAP'},
    {'label': 'ABC', 'value': 'ABC'},
    {'label': 'ActionScript', 'value': 'ActionScript'},
    {'label': 'ADA', 'value': 'ADA'},
    {'label': 'Apache_Conf', 'value': 'Apache_Conf'},
    {'label': 'AsciiDoc', 'value': 'AsciiDoc'},
    {'label': 'Assembly_x86', 'value': 'Assembly_x86'},
    {'label': 'AutoHotKey', 'value': 'AutoHotKey'},
    {'label': 'BatchFile', 'value': 'BatchFile'},
    {'label': 'C and C++', 'value': 'C_Cpp'},
    {'label': 'C9Search', 'value': 'C9Search'},
    {'label': 'Cirru', 'value': 'Cirru'},
    {'label': 'Clojure', 'value': 'Clojure'},
    {'label': 'Cobol', 'value': 'Cobol'},
    {'label': 'CoffeeScript', 'value': 'coffee'},
    {'label': 'ColdFusion', 'value': 'ColdFusion'},
    {'label': 'C#', 'value': 'CSharp'},
    {'label': 'CSS', 'value': 'CSS'},
    {'label': 'Curly', 'value': 'Curly'},
    {'label': 'D', 'value': 'D'},
    {'label': 'Dart', 'value': 'Dart'},
    {'label': 'Diff', 'value': 'Diff'},
    {'label': 'Dockerfile', 'value': 'Dockerfile'},
    {'label': 'Dot', 'value': 'Dot'},
    {'label': 'Dummy', 'value': 'Dummy'},
    {'label': 'DummySyntax', 'value': 'DummySyntax'},
    {'label': 'Eiffel', 'value': 'Eiffel'},
    {'label': 'EJS', 'value': 'EJS'},
    {'label': 'Elixir', 'value': 'Elixir'},
    {'label': 'Elm', 'value': 'Elm'},
    {'label': 'Erlang', 'value': 'Erlang'},
    {'label': 'Forth', 'value': 'Forth'},
    {'label': 'FreeMarker', 'value': 'FTL'},
    {'label': 'Gcode', 'value': 'Gcode'},
    {'label': 'Gherkin', 'value': 'Gherkin'},
    {'label': 'Gitignore', 'value': 'Gitignore'},
    {'label': 'Glsl', 'value': 'Glsl'},
    {'label': 'Gobstones', 'value': 'Gobstones'},
    {'label': 'Go', 'value': 'golang'},
    {'label': 'Groovy', 'value': 'Groovy'},
    {'label': 'HAML', 'value': 'HAML'},
    {'label': 'Handlebars', 'value': 'Handlebars'},
    {'label': 'Haskell', 'value': 'Haskell'},
    {'label': 'haXe', 'value': 'haXe'},
    {'label': 'HTML', 'value': 'HTML'},
    {'label': 'HTML (Elixir)', 'value': 'HTML_Elixir'},
    {'label': 'HTML (Ruby)', 'value': 'HTML_Ruby'},
    {'label': 'INI', 'value': 'INI'},
    {'label': 'Io', 'value': 'Io'},
    {'label': 'Jack', 'value': 'Jack'},
    {'label': 'Jade', 'value': 'Jade'},
    {'label': 'Java', 'value': 'Java'},
    {'label': 'JavaScript', 'value': 'JavaScript'},
    {'label': 'JSON', 'value': 'JSON'},
    {'label': 'JSONiq', 'value': 'JSONiq'},
    {'label': 'JSP', 'value': 'JSP'},
    {'label': 'JSX', 'value': 'JSX'},
    {'label': 'Julia', 'value': 'Julia'},
    {'label': 'LaTeX', 'value': 'LaTeX'},
    {'label': 'Lean', 'value': 'Lean'},
    {'label': 'LESS', 'value': 'LESS'},
    {'label': 'Liquid', 'value': 'Liquid'},
    {'label': 'Lisp', 'value': 'Lisp'},
    {'label': 'LiveScript', 'value': 'LiveScript'},
    {'label': 'LogiQL', 'value': 'LogiQL'},
    {'label': 'LSL', 'value': 'LSL'},
    {'label': 'Lua', 'value': 'Lua'},
    {'label': 'LuaPage', 'value': 'LuaPage'},
    {'label': 'Lucene', 'value': 'Lucene'},
    {'label': 'Makefile', 'value': 'Makefile'},
    {'label': 'Markdown', 'value': 'Markdown'},
    {'label': 'Mask', 'value': 'Mask'},
    {'label': 'MATLAB', 'value': 'MATLAB'},
    {'label': 'Maze', 'value': 'Maze'},
    {'label': 'MEL', 'value': 'MEL'},
    {'label': 'MUSHCode', 'value': 'MUSHCode'},
    {'label': 'MySQL', 'value': 'MySQL'},
    {'label': 'Nix', 'value': 'Nix'},
    {'label': 'NSIS', 'value': 'NSIS'},
    {'label': 'Objective-C', 'value': 'ObjectiveC'},
    {'label': 'OCaml', 'value': 'OCaml'},
    {'label': 'Pascal', 'value': 'Pascal'},
    {'label': 'Perl', 'value': 'Perl'},
    {'label': 'pgSQL', 'value': 'pgSQL'},
    {'label': 'PHP', 'value': 'PHP'},
    {'label': 'Powershell', 'value': 'Powershell'},
    {'label': 'Praat', 'value': 'Praat'},
    {'label': 'Prolog', 'value': 'Prolog'},
    {'label': 'Properties', 'value': 'Properties'},
    {'label': 'Protobuf', 'value': 'Protobuf'},
    {'label': 'Python', 'value': 'Python'},
    {'label': 'R', 'value': 'R'},
    {'label': 'Razor', 'value': 'Razor'},
    {'label': 'RDoc', 'value': 'RDoc'},
    {'label': 'RHTML', 'value': 'RHTML'},
    {'label': 'RST', 'value': 'RST'},
    {'label': 'Ruby', 'value': 'Ruby'},
    {'label': 'Rust', 'value': 'Rust'},
    {'label': 'SASS', 'value': 'SASS'},
    {'label': 'SCAD', 'value': 'SCAD'},
    {'label': 'Scala', 'value': 'Scala'},
    {'label': 'Scheme', 'value': 'Scheme'},
    {'label': 'SCSS', 'value': 'SCSS'},
    {'label': 'SH', 'value': 'SH'},
    {'label': 'SJS', 'value': 'SJS'},
    {'label': 'Smarty', 'value': 'Smarty'},
    {'label': 'snippets', 'value': 'snippets'},
    {'label': 'Soy_Template', 'value': 'Soy_Template'},
    {'label': 'Space', 'value': 'Space'},
    {'label': 'SQL', 'value': 'SQL'},
    {'label': 'SQLServer', 'value': 'SQLServer'},
    {'label': 'Stylus', 'value': 'Stylus'},
    {'label': 'SVG', 'value': 'SVG'},
    {'label': 'Swift', 'value': 'Swift'},
    {'label': 'Tcl', 'value': 'Tcl'},
    {'label': 'Tex', 'value': 'Tex'},
    {'label': 'Text', 'value': 'Text'},
    {'label': 'Textile', 'value': 'Textile'},
    {'label': 'Toml', 'value': 'Toml'},
    {'label': 'Twig', 'value': 'Twig'},
    {'label': 'Typescript', 'value': 'Typescript'},
    {'label': 'Vala', 'value': 'Vala'},
    {'label': 'VBScript', 'value': 'VBScript'},
    {'label': 'Velocity', 'value': 'Velocity'},
    {'label': 'Verilog', 'value': 'Verilog'},
    {'label': 'VHDL', 'value': 'VHDL'},
    {'label': 'Wollok', 'value': 'Wollok'},
    {'label': 'XML', 'value': 'XML'},
    {'label': 'XQuery', 'value': 'XQuery'},
    {'label': 'YAML', 'value': 'YAML'},
    {'label': 'Django', 'value': 'Django'}
]

AppConfig.prism_languages = [
    {'label': 'Markup', 'value': 'html'},
    {'label': 'CSS', 'value': 'css'},
    {'label': 'C-like', 'value': 'clike'},
    {'label': 'JavaScript', 'value': 'javascript'},
    {'label': 'ABAP', 'value': 'abap'},
    {'label': 'ActionScript', 'value': 'actionscript'},
    {'label': 'Ada', 'value': 'ada'},
    {'label': 'Apache Configuration', 'value': 'apacheconf'},
    {'label': 'APL', 'value': 'apl'},
    {'label': 'AppleScript', 'value': 'applescript'},
    {'label': 'AsciiDoc', 'value': 'asciidoc'},
    {'label': 'ASP.NET (C#)', 'value': 'aspnet'},
    {'label': 'AutoIt', 'value': 'autoit'},
    {'label': 'AutoHotkey', 'value': 'autohotkey'},
    {'label': 'Bash', 'value': 'bash'},
    {'label': 'BASIC', 'value': 'basic'},
    {'label': 'Batch', 'value': 'batch'},
    {'label': 'Bison', 'value': 'bison'},
    {'label': 'Brainfuck', 'value': 'brainfuck'},
    {'label': 'Bro', 'value': 'bro'},
    {'label': 'C', 'value': 'c'},
    {'label': 'C#', 'value': 'csharp'},
    {'label': 'C++', 'value': 'cpp'},
    {'label': 'CoffeeScript', 'value': 'coffeescript'},
    {'label': 'Crystal', 'value': 'crystal'},
    {'label': 'CSS Extras', 'value': 'css-extras'},
    {'label': 'D', 'value': 'd'},
    {'label': 'Dart', 'value': 'dart'},
    {'label': 'Diff', 'value': 'diff'},
    {'label': 'Docker', 'value': 'docker'},
    {'label': 'Eiffel', 'value': 'eiffel'},
    {'label': 'Elixir', 'value': 'elixir'},
    {'label': 'Erlang', 'value': 'erlang'},
    {'label': 'F#', 'value': 'fsharp'},
    {'label': 'Fortran', 'value': 'fortran'},
    {'label': 'Gherkin', 'value': 'gherkin'},
    {'label': 'Git', 'value': 'git'},
    {'label': 'GLSL', 'value': 'glsl'},
    {'label': 'Go', 'value': 'go'},
    {'label': 'GraphQL', 'value': 'graphql'},
    {'label': 'Groovy', 'value': 'groovy'},
    {'label': 'Haml', 'value': 'haml'},
    {'label': 'Handlebars', 'value': 'handlebars'},
    {'label': 'Haskell', 'value': 'haskell'},
    {'label': 'Haxe', 'value': 'haxe'},
    {'label': 'HTTP', 'value': 'http'},
    {'label': 'Icon', 'value': 'icon'},
    {'label': 'Inform 7', 'value': 'inform7'},
    {'label': 'Ini', 'value': 'ini'},
    {'label': 'J', 'value': 'j'},
    {'label': 'Jade', 'value': 'jade'},
    {'label': 'Java', 'value': 'java'},
    {'label': 'JSON', 'value': 'json'},
    {'label': 'Julia', 'value': 'julia'},
    {'label': 'Keyman', 'value': 'keyman'},
    {'label': 'Kotlin', 'value': 'kotlin'},
    {'label': 'LaTeX', 'value': 'latex'},
    {'label': 'Less', 'value': 'less'},
    {'label': 'LiveScript', 'value': 'livescript'},
    {'label': 'LOLCODE', 'value': 'lolcode'},
    {'label': 'Lua', 'value': 'lua'},
    {'label': 'Makefile', 'value': 'makefile'},
    {'label': 'Markdown', 'value': 'markdown'},
    {'label': 'MATLAB', 'value': 'matlab'},
    {'label': 'MEL', 'value': 'mel'},
    {'label': 'Mizar', 'value': 'mizar'},
    {'label': 'Monkey', 'value': 'monkey'},
    {'label': 'NASM', 'value': 'nasm'},
    {'label': 'nginx', 'value': 'nginx'},
    {'label': 'Nim', 'value': 'nim'},
    {'label': 'Nix', 'value': 'nix'},
    {'label': 'NSIS', 'value': 'nsis'},
    {'label': 'Objective-C', 'value': 'objectivec'},
    {'label': 'OCaml', 'value': 'ocaml'},
    {'label': 'Oz', 'value': 'oz'},
    {'label': 'PARI/GP', 'value': 'parigp'},
    {'label': 'Parser', 'value': 'parser'},
    {'label': 'Pascal', 'value': 'pascal'},
    {'label': 'Perl', 'value': 'perl'},
    {'label': 'PHP', 'value': 'php'},
    {'label': 'PHP Extras', 'value': 'php-extras'},
    {'label': 'PowerShell', 'value': 'powershell'},
    {'label': 'Processing', 'value': 'processing'},
    {'label': 'Prolog', 'value': 'prolog'},
    {'label': '.properties', 'value': 'properties'},
    {'label': 'Protocol Buffers', 'value': 'protobuf'},
    {'label': 'Puppet', 'value': 'puppet'},
    {'label': 'Pure', 'value': 'pure'},
    {'label': 'Python', 'value': 'python'},
    {'label': 'Q', 'value': 'q'},
    {'label': 'Qore', 'value': 'qore'},
    {'label': 'R', 'value': 'r'},
    {'label': 'React JSX', 'value': 'jsx'},
    {'label': 'reST (reStructuredText)', 'value': 'rest'},
    {'label': 'Rip', 'value': 'rip'},
    {'label': 'Roboconf', 'value': 'roboconf'},
    {'label': 'Ruby', 'value': 'ruby'},
    {'label': 'Rust', 'value': 'rust'},
    {'label': 'SAS', 'value': 'sas'},
    {'label': 'Sass (Sass)', 'value': 'sass'},
    {'label': 'Sass (Scss)', 'value': 'scss'},
    {'label': 'Scala', 'value': 'scala'},
    {'label': 'Scheme', 'value': 'scheme'},
    {'label': 'Smalltalk', 'value': 'smalltalk'},
    {'label': 'Smarty', 'value': 'smarty'},
    {'label': 'SQL', 'value': 'sql'},
    {'label': 'Stylus', 'value': 'stylus'},
    {'label': 'Swift', 'value': 'swift'},
    {'label': 'Tcl', 'value': 'tcl'},
    {'label': 'Textile', 'value': 'textile'},
    {'label': 'Twig', 'value': 'twig'},
    {'label': 'TypeScript', 'value': 'typescript'},
    {'label': 'Verilog', 'value': 'verilog'},
    {'label': 'VHDL', 'value': 'vhdl'},
    {'label': 'vim', 'value': 'vim'},
    {'label': 'Wiki markup', 'value': 'wiki'},
    {'label': 'Xojo (REALbasic)', 'value': 'xojo'},
    {'label': 'YAML', 'value': 'yaml'}
]

export default AppConfig
